---
:project:
  :use_exceptions: TRUE
  :use_test_preprocessor: TRUE
  :use_auxiliary_dependencies: TRUE
  :build_root: build
  :release_build: TRUE
  :test_file_prefix: test_
  :which_ceedling: gem
  :ceedling_version: 0.31.1
  :default_tasks:
    - release

:release_build:
  :output: Cbject.out

:environment:

:extension:
  :executable: .out

:paths:
  :test:
    - +:test/**
    - -:test/support
  :source:
    - src/**
  :support:
    - test/support
  :libraries: []

:defines:
  :common: &common_defines []
  :test:
    - *common_defines
    - TEST
  :test_preprocess:
    - *common_defines
    - TEST

:flags:
  :release:
    :compile:
      :*:
        # - -save-temps
        - -std=c99
        - -Wall -Wextra -Werror
        - -g

:cmock:
  :mock_prefix: mock_
  :when_no_prototypes: :warn
  :when_ptr: :compare_ptr
  :enforce_strict_ordering: TRUE
  :plugins:
    - :ignore
    - :callback
    - :ignore_arg
  :treat_externs: :include
  :treat_as:
    uint8_t: HEX8
    uint16: HEX16
    uint32_t: UINT32
    int8: INT8
    bool: UINT8

:gcov:
  :reports:
    - HtmlDetailed
  :gcovr:
    :html_medium_threshold: 75
    :html_high_threshold: 90

:libraries:
  :placement: :end
  :flag: "-l${1}"
  :path_flag: "-L ${1}"
  :system: []
  :test: []
  :release: []

:plugins:
  :load_paths:
    - "#{Ceedling.load_path}"
  :enabled:
    # - stdout_pretty_tests_report
    - stdout_gtestlike_tests_report
    - module_generator
    - gcov
    - xml_tests_report
